### ISSUE TITLE
Bug: PL not starting anymore

### ISSUE THREAD

**Issue by Shrekmachine** [isaacrlevin/PresenceLight#19]
I tried to reinstall but it is saying that I'm trying to install version 1.0.50 when I download from the nightly build (v 1.0.163)
However, both versions are not starting since this morning anymore.

**Comment by Dutchgroover** [comment]
Got the same problem on 2 pc's since today. It is not starting anymore and writes an entry in Event viewer. 


Naam van toepassing met fout: PresenceLight.exe, versie: 1.0.0.0, tijdstempel: 0x5e96518b
Naam van module met fout: KERNELBASE.dll, versie: 10.0.18362.778, tijdstempel: 0x692cf0ab
Uitzonderingscode: 0xe0434352
Foutmarge: 0x00114192
Id van proces met fout: 0x7e5c
Starttijd van toepassing met fout: 0x01d623a7d2195196
Pad naar toepassing met fout: C:\Program Files\WindowsApps\37828IsaacLevin.197278F15330A.Nightly_1.0.150.0_x86__jvewcxq8vj8qt\PresenceLight\PresenceLight.exe
Pad naar module met fout: C:\WINDOWS\System32\KERNELBASE.dll
Rapport-id: a5afa8b0-2c53-436d-ae15-05c256eb735d
Volledige pakketnaam met fout: 37828IsaacLevin.197278F15330A.Nightly_1.0.150.0_x86__jvewcxq8vj8qt
Relatieve toepassings-id van pakket met fout: App

**Comment by isaacrlevin** [comment]
Anything in Event log? I just did a test with no issue

**Comment by Shrekmachine** [comment]
Could it be the build? I have 2004 (19041.208)

**Comment by Dutchgroover** [comment]
I installed it on monday and it work fine. Today is doesn't. When trying to reinstall from the website is says that there is already a newer version. Did Uninstall and that a new install but problem is the same.
It starts in Task monitor and the gives a Microsoft error and stops.  Some extra info from eventviewer: (dutch version)

Application: PresenceLight.exe
CoreCLR Version: 5.0.20.21406
.NET Version: 5.0.0-preview.3.20214.6
Description: The process was terminated due to an unhandled exception.
Exception Info: Microsoft.Azure.Services.AppAuthentication.AzureServiceTokenProviderException: Parameters: Connection String: [No connection string specified], Resource: https://vault.azure.net, Authority: https://login.windows.net/72f988bf-86f1-41af-91ab-2d7cd011db47. Exception Message: Tried the following 3 methods to get an access token, but none of them worked.
Parameters: Connection String: [No connection string specified], Resource: https://vault.azure.net, Authority: https://login.windows.net/72f988bf-86f1-41af-91ab-2d7cd011db47. Exception Message: Tried to get token using Managed Service Identity. Unable to connect to the Managed Service Identity (MSI) endpoint. Please check that you are running on an Azure resource that has MSI setup.
Parameters: Connection String: [No connection string specified], Resource: https://vault.azure.net, Authority: https://login.windows.net/72f988bf-86f1-41af-91ab-2d7cd011db47. Exception Message: Tried to get token using Visual Studio. Access token could not be acquired. Visual Studio Token provider file not found at "C:\Users\roald.000\AppData\Local\.IdentityService\AzureServiceAuth\tokenprovider.json"
Parameters: Connection String: [No connection string specified], Resource: https://vault.azure.net, Authority: https://login.windows.net/72f988bf-86f1-41af-91ab-2d7cd011db47. Exception Message: Tried to get token using Azure CLI. Access token could not be acquired. 'az' is not recognized as an internal or external command,
operable program or batch file.

**Comment by isaacrlevin** [comment]
Do a full uninstall and reinstall. The new version is 1.0.152.0

**Comment by Shrekmachine** [comment]
New version not starting for me after reinstall

**Comment by Shrekmachine** [comment]
Application: PresenceLight.exe
CoreCLR Version: 5.0.20.21406
.NET Version: 5.0.0-preview.3.20214.6
Description: The process was terminated due to an unhandled exception.
Exception Info: Microsoft.Azure.Services.AppAuthentication.AzureServiceTokenProviderException: Parameters: Connection String: [No connection string specified], Resource: https://vault.azure.net, Authority: https://login.windows.net/72f988bf-86f1-41af-91ab-2d7cd011db47. Exception Message: Tried the following 3 methods to get an access token, but none of them worked.
Parameters: Connection String: [No connection string specified], Resource: https://vault.azure.net, Authority: https://login.windows.net/72f988bf-86f1-41af-91ab-2d7cd011db47. Exception Message: Tried to get token using Managed Service Identity. Unable to connect to the Managed Service Identity (MSI) endpoint. Please check that you are running on an Azure resource that has MSI setup.
Parameters: Connection String: [No connection string specified], Resource: https://vault.azure.net, Authority: https://login.windows.net/72f988bf-86f1-41af-91ab-2d7cd011db47. Exception Message: Tried to get token using Visual Studio. Access token could not be acquired. 
Parameters: Connection String: [No connection string specified], Resource: https://vault.azure.net, Authority: https://login.windows.net/72f988bf-86f1-41af-91ab-2d7cd011db47. Exception Message: Tried to get token using Azure CLI. Access token could not be acquired. Der Befehl "az" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.


   at Microsoft.Azure.Services.AppAuthentication.AzureServiceTokenProvider.GetAccessTokenAsyncImpl(String authority, String resource, String scope)
   at Microsoft.Azure.KeyVault.KeyVaultCredential.PostAuthenticate(HttpResponseMessage response)
   at Microsoft.Azure.KeyVault.KeyVaultCredential.ProcessHttpRequestAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Azure.KeyVault.KeyVaultClient.GetSecretsWithHttpMessagesAsync(String vaultBaseUrl, Nullable`1 maxresults, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Azure.KeyVault.KeyVaultClientExtensions.GetSecretsAsync(IKeyVaultClient operations, String vaultBaseUrl, Nullable`1 maxresults, CancellationToken cancellationToken)
   at Microsoft.Extensions.Configuration.AzureKeyVault.AzureKeyVaultConfigurationProvider.LoadAsync()
   at Microsoft.Extensions.Configuration.AzureKeyVault.AzureKeyVaultConfigurationProvider.Load()
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at PresenceLight.App.OnStartup(Object sender, StartupEventArgs e) in d:\a\1\s\src\PresenceLight\App.xaml.cs:line 47
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
   at PresenceLight.App.Main()

**Comment by Dutchgroover** [comment]
Tested it on 2 pc's but still not running. Same kind of error as above.

**Comment by isaacrlevin** [comment]
Confirm that this file
C:\Users\username\AppData\Local\Packages\37828IsaacLevin.197278F15330A.Nightly_jvewcxq8vj8qt\LocalState\settings.json

matches this schema

```json
{
  "ClientId": "f8119f58-4523-44c1-ab72-b2e0c815bd6a",
  "LIFXApiKey": "",
  "ClientSecret": "",
  "Instance": "https://login.microsoftonline.com/",
  "RedirectUri": "http://localhost",
  "CallbackPath": "/signin-oidc",
  "HueApiKey": "",
  "LIFXClientId": "",
  "LIFXClientSecret": "",
  "ApiScopes": "User.Read offline_access",
  "PollingInterval": 5.0,
  "Brightness": 100,
  "SelectedHueLightId": "",
  "SelectedLIFXItemId": "",
  "HueIpAddress": "",
  "IconType": "White",
  "IsLIFXEnabled": false,
  "IsPhillipsEnabled": false,
  "KeyVaultName": "presencelight-kv"
}
````

**Comment by Shrekmachine** [comment]
folder is empty

**Comment by isaacrlevin** [comment]
There should be a json file there. Check for this file

C:\Program Files\WindowsApps\37828IsaacLevin.197278F15330A.Nightly_1.0.154.0_x86__jvewcxq8vj8qt\PresenceLight\appsettings.json

**Comment by Shrekmachine** [comment]
trust me. empty folder.

**Comment by isaacrlevin** [comment]
what about the program files folder?

**Comment by Shrekmachine** [comment]
pls check Teams

**Comment by isaacrlevin** [comment]
This is now resolved

**Comment by Shrekmachine** [comment]
indeed1.0.155.0 is working again.
Thanks
