### ISSUE TITLE
Worker install - "Invalid RedirectURI was received (/signin-oidc)"

### ISSUE THREAD

**Issue by gooman-uk** [isaacrlevin/presencelight#454]
**Describe the bug**
On first install of the Worker, I get:

```
Stopped program because of exception

System.InvalidOperationException: Invalid RedirectURI was received (/signin-oidc)  Not parseable into System.Uri class.

```
Followed by a stack trace and then the console window closes before I can copy it.

## Further details
- OS: Windows 10
- PresenceLight App Type - Worker
- PresenceLight Build - https://presencelightapp.azurewebsites.net/
- PresenceLight Version (The # in About) - don't get that far!
- Did you clear settings.json? (C:\Users\username\AppData\Local\Packages\37828IsaacLevin.197278F15330A.SomeValue\LocalState\settings.json - there is no such folder in Packages - presumably it didn't get that far
- ASP.NET Core version - v5

**Comment by stephendelucia** [comment]
Same issue here, would love to know if you found a solution.  Tried running as administrator as well.

**Comment by isaacrlevin** [comment]
Sorry for the delay, are you running in Docker?

**Comment by stephendelucia** [comment]
> 
> 
> Sorry for the delay, are you running in Docker?

Nope.  But I am running on my work computer which blocks some connections (zscaler), not sure if that is it.

**Comment by gooman-uk** [comment]
Nope, me neither. Just Windows 10.On 16 Sep 2021 19:05, Isaac Levin ***@***.***> wrote:
Sorry for the delay, are you running in Docker?

**Comment by isaacrlevin** [comment]
Try this, go into the folder with the .exe in it and update *RedirectHost* to `https://localhost:5001`. I noticed that field is empty when I downloaded it

**Comment by stephendelucia** [comment]
> 
> 
> Try this, go into the folder with the .exe in it and update _RedirectHost_ to `https://localhost:5001`. I noticed that field is empty when I downloaded it

So that definitely fixed the original error, but now I am getting a different one:

`[12:12:14 INF] User profile is available. Using 'C:\Users\XXXXXXXX\AppData\Local\ASP.NET\DataProtection-Keys' as key repository and Windows DPAPI to encrypt keys at rest.
[12:12:14 INF] User is Not Authenticated, restarting worker - Worker:ExecuteAsync Line: 65
[12:12:15 FTL] Unable to start Kestrel.
System.InvalidOperationException: Unable to configure HTTPS endpoint. No server certificate was specified, and the default developer certificate could not be found or is out of date.
To generate a developer certificate run 'dotnet dev-certs https'. To trust the certificate (Windows and macOS only) run 'dotnet dev-certs https --trust'.
For more information on configuring HTTPS see https://go.microsoft.com/fwlink/?linkid=848054.
   at Microsoft.AspNetCore.Hosting.ListenOptionsHttpsExtensions.UseHttps(ListenOptions listenOptions, Action`1 configureOptions)
   at Microsoft.AspNetCore.Hosting.ListenOptionsHttpsExtensions.UseHttps(ListenOptions listenOptions)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.AddressesStrategy.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IEnumerable`1 listenOptions, AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.BindAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
[12:12:15 INF] User is Not Authenticated, restarting worker - Worker:ExecuteAsync Line: 65
[12:12:15 ERR] Stopped program because of exception
System.InvalidOperationException: Unable to configure HTTPS endpoint. No server certificate was specified, and the default developer certificate could not be found or is out of date.
To generate a developer certificate run 'dotnet dev-certs https'. To trust the certificate (Windows and macOS only) run 'dotnet dev-certs https --trust'.
For more information on configuring HTTPS see https://go.microsoft.com/fwlink/?linkid=848054.
   at Microsoft.AspNetCore.Hosting.ListenOptionsHttpsExtensions.UseHttps(ListenOptions listenOptions, Action`1 configureOptions)
   at Microsoft.AspNetCore.Hosting.ListenOptionsHttpsExtensions.UseHttps(ListenOptions listenOptions)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.AddressesStrategy.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IEnumerable`1 listenOptions, AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.BindAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at PresenceLight.Worker.Program.Main(String[] args)
`

**Comment by stephendelucia** [comment]
ahhhh - it works!   I had to install [dotnet](https://aka.ms/dotnet-download) first and then run those 2 commands.  then it started up.  

I was expecting a UI to pop up automatically but once I went to localhost:5001 it appears to be running properly.  Now to mess around and get this working!

THANK YOU!!!
