### ISSUE TITLE
Crashing when trying to access Custom API Setup in worker

### ISSUE THREAD

**Issue by BobBuildingCode** [isaacrlevin/presencelight#465]
**Describe the bug**
When I click on Custom API Setup in worker I just get `An error has occurred. This application may no longer respond until reloaded. Reload` and it stops working. Happens every time I try to reach https://localhost:5001/customapi.

**To Reproduce**
Open up https://localhost:5001/ and click on Custom API Setup
or
Open up https://localhost:5001/customapi

**Logs**
`[09:59:34 WRN] Unhandled exception rendering component: Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Object.GetType()
   at PresenceLight.Worker.Pages.CustomApiSetup.BuildRenderTree(RenderTreeBuilder __builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderInExistingBatch(RenderQueueEntry renderQueueEntry)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
[09:59:34 ERR] Unhandled exception in circuit 'ukJZrnPSLGyKo1RlGpXjZFzlw9cH3dKNIyQjO270FsA'.
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Object.GetType()
   at PresenceLight.Worker.Pages.CustomApiSetup.BuildRenderTree(RenderTreeBuilder __builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderInExistingBatch(RenderQueueEntry renderQueueEntry)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()`

## Further details
- OS: Windows 10
- PresenceLight Version: Worker v4.2.28
- Did you clear settings.json: Where is this on the Worker?
- ASP.NET Core version: Microsoft.AspNetCore.App 5.0.10

**Comment by isaacrlevin** [comment]
Fixed bug, newest nightly should have fix
