### ISSUE TITLE
Install PresenceLight on Raspbian without Docker

### ISSUE THREAD

**Issue by thor1466** [isaacrlevin/presencelight#598]
Hi Isaac

Is it possible to install PresenceLight on Raspbian without Docker?
I can see that you have made a version at the download site which is for ARM Linux 32 bit.

I dont know what to do with the downloaded .zip file?
Can you help?

Best regards
Thor1466

**Comment by isaacrlevin** [comment]
You would need to extract that zip file (might need to update the file permissions) and just run the PresenceLight file from terminal. Than you would open a browser on the Pi and go to http://localhost:5000 and auth as usual

**Comment by thor1466** [comment]
Thanks a lot! I needed to update file permissions, and then thinks worked out! 

New problem/question:
After signing in to login.microsoftonline.com it goes into a loop, just updating page over and over saying "trying to log in"

Please help, I would love to finish it in RasPi
Best regards

**Comment by thor1466** [comment]
Hi Isaac
Thanks for your reply im so grateful👍 
Here's what's going on i terminal:

pi@raspberrypi:~ $ sudo cd /home/pi/Downloads/PresenceLight.5.0.13_Linux_ARM
sudo: cd: command not found
pi@raspberrypi:~ $ cd /home/pi/Downloads/PresenceLight.5.0.13_Linux_ARM
pi@raspberrypi:~/Downloads/PresenceLight.5.0.13_Linux_ARM $ ./PresenceLight
[16:50:58 INF] User profile is available. Using '/home/pi/.aspnet/DataProtection-Keys' as key repository; keys will not be encrypted at rest.
[16:51:04 INF] User is Not Authenticated, restarting worker - Worker:ExecuteAsync Line: 59
[16:51:05 INF] Now listening on: http://localhost:5000
[16:51:05 INF] Application started. Press Ctrl+C to shut down.
[16:51:05 INF] Hosting environment: Production
[16:51:05 INF] Content root path: /home/pi/Downloads/PresenceLight.5.0.13_Linux_ARM/
[16:51:05 INF] User is Not Authenticated, restarting worker - Worker:ExecuteAsync Line: 59
[16:51:06 INF] User is Not Authenticated, restarting worker - Worker:ExecuteAsync Line: 59
[16:51:07 INF] User is Not Authenticated, restarting worker - Worker:ExecuteAsync Line: 59
[16:51:08 INF] User is Not Authenticated, restarting worker - Worker:ExecuteAsync Line: 59
[16:51:09 INF] User is Not Authenticated, restarting worker - Worker:ExecuteAsync Line: 59
[16:51:10 INF] User is Not Authenticated, restarting worker - Worker:ExecuteAsync Line: 59
[16:51:11 INF] User is Not Authenticated, restarting worker - Worker:ExecuteAsync Line: 59
[16:51:12 INF] User is Not Authenticated, restarting worker - Worker:ExecuteAsync Line: 59
[16:51:13 INF] User is Not Authenticated, restarting worker - Worker:ExecuteAsync Line: 59
[16:51:14 INF] User is Not Authenticated, restarting worker - Worker:ExecuteAsync Line: 59
[16:51:15 INF] User is Not Authenticated, restarting worker - Worker:ExecuteAsync Line: 59
[16:51:16 INF] User is Not Authenticated, restarting worker - Worker:ExecuteAsync Line: 59
[16:51:17 INF] User is Not Authenticated, restarting worker - Worker:ExecuteAsync Line: 59
[16:51:18 INF] User is Not Authenticated, restarting worker - Worker:ExecuteAsync Line: 59
[16:51:19 INF] User is Not Authenticated, restarting worker - Worker:ExecuteAsync Line: 59
[16:51:20 INF] User is Not Authenticated, restarting worker - Worker:ExecuteAsync Line: 59
[16:51:21 INF] User is Not Authenticated, restarting worker - Worker:ExecuteAsync Line: 59
[16:51:22 INF] User is Not Authenticated, restarting worker - Worker:ExecuteAsync Line: 59
[16:51:23 INF] User is Not Authenticated, restarting worker - Worker:ExecuteAsync Line: 59
[16:51:24 INF] User is Not Authenticated, restarting worker - Worker:ExecuteAsync Line: 59
[16:51:25 INF] User is Not Authenticated, restarting worker - Worker:ExecuteAsync Line: 59
[16:51:26 INF] User is Not Authenticated, restarting worker - Worker:ExecuteAsync Line: 59
[16:51:26 INF] Request starting HTTP/1.1 GET http://localhost:5000/ - -
[16:51:26 WRN] Failed to determine the https port for redirect.
[16:51:27 INF] User is Not Authenticated, restarting worker - Worker:ExecuteAsync Line: 59
[16:51:28 INF] User is Not Authenticated, restarting worker - Worker:ExecuteAsync Line: 59
[16:51:28 INF] OpenIdConnect was not authenticated. Failure message: Not authenticated
[16:51:29 INF] Authorization failed. These requirements were not met:
DenyAnonymousAuthorizationRequirement: Requires an authenticated user.
[16:51:29 INF] User is Not Authenticated, restarting worker - Worker:ExecuteAsync Line: 59
[16:51:30 INF] User is Not Authenticated, restarting worker - Worker:ExecuteAsync Line: 59
[16:51:31 INF] User is Not Authenticated, restarting worker - Worker:ExecuteAsync Line: 59
[16:51:32 INF] User is Not Authenticated, restarting worker - Worker:ExecuteAsync Line: 59
[16:51:33 INF] User is Not Authenticated, restarting worker - Worker:ExecuteAsync Line: 59
[16:51:34 INF] User is Not Authenticated, restarting worker - Worker:ExecuteAsync Line: 59
[16:51:35 INF] User is Not Authenticated, restarting worker - Worker:ExecuteAsync Line: 59
[16:51:36 WRN] The cookie '.AspNetCore.OpenIdConnect.Nonce.CfDJ8F-NScfXZghCkJxo3lDgi24OchHAHI0e8PtZVYJen43MB8o4eomy58ZFdGpktTHP2ylxbXVidK5sCXBymuEsnQidEvgiETZMzdFv3Bv2VkdSJQ3JNzu24NTtQHDS1rk6Moy9gBxLfViHn8ATBNzHq0wZaO_LlQoAI8YH3tKkFIpdSd17df2DrALH2aQF-89irsRRUEqxgDFn37BzjFB7NMWlkkmg4LurWvcDA9QT0Lz_oi8xEjGK9uM-zcGqxwCCsnoDCD8SHzn0iAHkR4IYTPI' has set 'SameSite=None' and must also set 'Secure'.
[16:51:36 WRN] The cookie '.AspNetCore.Correlation.0QjooDGw6z1EWo5VUJtmUA4fjqvhRiNycUcfqajjATM' has set 'SameSite=None' and must also set 'Secure'.
[16:51:36 INF] AuthenticationScheme: OpenIdConnect was challenged.
[16:51:36 INF] User is Not Authenticated, restarting worker - Worker:ExecuteAsync Line: 59
[16:51:36 INF] Request finished HTTP/1.1 GET http://localhost:5000/ - - - 302 0 - 10202.0164ms
[16:51:37 INF] User is Not Authenticated, restarting worker - Worker:ExecuteAsync Line: 59
[16:51:38 INF] User is Not Authenticated, restarting worker - Worker:ExecuteAsync Line: 59
[16:51:38 INF] Request starting HTTP/1.1 POST http://localhost:5000/signin-oidc application/x-www-form-urlencoded 1309
[16:51:39 WRN] '.AspNetCore.Correlation.0QjooDGw6z1EWo5VUJtmUA4fjqvhRiNycUcfqajjATM' cookie not found.
[16:51:39 INF] Error from RemoteAuthentication: Correlation failed..
[16:51:39 ERR] An unhandled exception has occurred while executing the request.
System.Exception: An error was encountered while handling the remote login.
 ---> System.Exception: Correlation failed.
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.HandleRequestAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
[16:51:39 INF] User is Not Authenticated, restarting worker - Worker:ExecuteAsync Line: 59
[16:51:40 INF] OpenIdConnect was not authenticated. Failure message: Not authenticated
[16:51:40 INF] Authorization failed. These requirements were not met:
DenyAnonymousAuthorizationRequirement: Requires an authenticated user.
[16:51:40 WRN] The cookie '.AspNetCore.OpenIdConnect.Nonce.CfDJ8F-NScfXZghCkJxo3lDgi25FTBZXKRxZg1RBUuMk6oo0u4r5yfqi8H7FfaaEj2MkBpG-_aqVdEe5x36t2aNRTw0iU7F3WKdRcdHvtEAt7SCHzuD4eHwM2pjv5HKwnB9oyPcbzQ5qlsDqQQFIfY26ojND9F3SIwUc6IFvWsTJvwzUr2l6kw9PWXL5NjF0vUrVTIVTuK50AWu6LuiG8551JWmJ7ZYOI52XSjqcHpAoDNk_7QnOWpiCssqVcd1ZSgiNLax6VRKrq50yDJ90-F_nSPo' has set 'SameSite=None' and must also set 'Secure'.
[16:51:40 WRN] The cookie '.AspNetCore.Correlation.VjhvFDew3EemOslbhtmpPTQOb0Xm0UCFuGOgTCls_kU' has set 'SameSite=None' and must also set 'Secure'.
[16:51:40 INF] AuthenticationScheme: OpenIdConnect was challenged.
[16:51:40 INF] Request finished HTTP/1.1 POST http://localhost:5000/signin-oidc application/x-www-form-urlencoded 1309 - 302 0 - 1874.4159ms
[16:51:40 INF] User is Not Authenticated, restarting worker - Worker:ExecuteAsync Line: 59
[16:51:41 INF] Request starting HTTP/1.1 POST http://localhost:5000/signin-oidc application/x-www-form-urlencoded 1309
[16:51:41 WRN] '.AspNetCore.Correlation.VjhvFDew3EemOslbhtmpPTQOb0Xm0UCFuGOgTCls_kU' cookie not found.
[16:51:41 INF] Error from RemoteAuthentication: Correlation failed..
[16:51:41 ERR] An unhandled exception has occurred while executing the request.
System.Exception: An error was encountered while handling the remote login.
 ---> System.Exception: Correlation failed.


Hope you can help me out, thanks again.

Best regards
Thor1466

**Comment by thor1466** [comment]
> Try https://localhost:5001

“This site can’t be reached”

**Comment by isaacrlevin** [comment]
Did you follow the prereqs in the web readme?
https://github.com/isaacrlevin/PresenceLight/blob/main/web-README.md

**Comment by thor1466** [comment]
> Did you follow the prereqs in the web readme?
> https://github.com/isaacrlevin/PresenceLight/blob/main/web-README.md

Every single step. Any ideas?
Regards

**Comment by thor1466** [comment]
> The part about getting a certificate
> 
> ![image](https://user-images.githubusercontent.com/8878502/154735217-3b22765e-3d5f-4392-8e2e-185b8a402fe0.png)

I worked things out. Had problems installing the dod net part. Thanks a lot for your support and fast replies! :-)
