### ISSUE TITLE
Must authenticate when docker container is restarted

### ISSUE THREAD

**Issue by CamSoper** [isaacrlevin/presencelight#599]
Repro:

1. Run with `docker-compose up -d`
2. Sign in to localhost:5001 and authenticate
3. Restart presencelight with `docker-compose restart`

Expected behavior: PresenceLight starts running with authentication from the previous run

Actual behavior: User must authenticate with PresenceLight again before PresenceLight can do its thing

**Comment by CamSoper** [comment]
Rewriting this issue to be an issue instead of rambling.

**Comment by CamSoper** [comment]
Microsoft Identity makes my head hurt. This might be relevant, I think? 

https://github.com/AzureAD/microsoft-identity-web/wiki/token-cache-serialization

**Comment by isaacrlevin** [comment]
I need to use a different caching mechanism I think.... Looking more into it

**Comment by isaacrlevin** [comment]
@CamSoper can you try the fix in this PR?

https://github.com/isaacrlevin/presencelight/pull/616

You will have to build the image and container but see if that resolves your issue

**Comment by CamSoper** [comment]
Will do. Give me a day or two.

**Comment by CamSoper** [comment]
@isaacrlevin Well, I tried. I can't get it built. If I try to `docker build ./PresenceLight.Web` at the CLI, it gets blows up on copying the csproj files. If I right-click on the Dockerfile and try to build, it gets to the end but then the PressenceLight.Web.csproj blows up complaining that the docker CLI isn't installed (it is).

I'm not out of tricks to try, I thought about just forking your repo and using your GH actions to build it, but if you could just tag a build from this PR "experimental" and push to Docker Hub, that'd probably save me some troubleshooting...

**Comment by CamSoper** [comment]
The docker build worked when I used your parameters. I'm not sure why your docker command worked and mine didn't. 

Anyway I tagged it as camsoper/camthegeek:pl-custom and sent it to my public docker hub (I actually run on my Ubuntu server, x64 FYI) and then used this docker-compose.yaml:

```yaml
version: '3.7'

services:
  presencelight:
    #image: isaaclevin/presencelight:latest
    image: camsoper/camthegeek:pl-custom
    container_name: presencelight
    restart: unless-stopped
    ports:
      - 5000:80
      - 5001:443
    volumes:
      - ./https:/https:ro
      - ./config:/app/config
      - ./aspnet:/root/.aspnet
    environment:
      ASPNETCORE_HTTPS_PORT: "5001"
      ASPNETCORE_URLS: "https://+;http://+"
      ASPNETCORE_Kestrel__Certificates__Default__Password: "presencelight"
      ASPNETCORE_Kestrel__Certificates__Default__Path: "/https/presencelight.pfx"
      Serilog__MinimumLevel: "Error"
```

Did a `docker-compose up` and it barfed thusly:

```
presencelight    | [19:35:16 ERR] An unhandled exception has occurred while executing the request.
presencelight    | System.ArgumentNullException: IDW10106: The 'ClientId' option must be provided. 
presencelight    |    at Microsoft.Identity.Web.MergedOptionsValidation.Validate(MergedOptions options)
presencelight    |    at Microsoft.Identity.Web.MicrosoftIdentityWebAppAuthenticationBuilderExtensions.<>c__DisplayClass5_0.<AddMicrosoftIdentityWebAppInternal>b__3(OpenIdConnectOptions options, IServiceProvider serviceProvider, IOptionsMonitor`1 mergedOptionsMonitor, IOptionsMonitor`1 msIdOptionsMonitor, IOptions`1 msIdOptions)
presencelight    |    at Microsoft.Extensions.Options.ConfigureNamedOptions`5.Configure(String name, TOptions options)
presencelight    |    at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
presencelight    |    at Microsoft.Extensions.Options.OptionsMonitor`1.<>c__DisplayClass10_0.<Get>b__0()
presencelight    |    at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
presencelight    |    at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
presencelight    |    at System.Lazy`1.CreateValue()
presencelight    |    at System.Lazy`1.get_Value()
presencelight    |    at Microsoft.Extensions.Options.OptionsCache`1.GetOrAdd(String name, Func`1 createOptions)
presencelight    |    at Microsoft.Extensions.Options.OptionsMonitor`1.Get(String name)
presencelight    |    at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.InitializeAsync(AuthenticationScheme scheme, HttpContext context)
presencelight    |    at Microsoft.AspNetCore.Authentication.AuthenticationHandlerProvider.GetHandlerAsync(HttpContext context, String authenticationScheme)
presencelight    |    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
presencelight    |    at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
presencelight    | [19:35:16 ERR] An exception was thrown attempting to execute the error handler.
presencelight    | System.ArgumentNullException: IDW10106: The 'ClientId' option must be provided. 
presencelight    |    at Microsoft.Identity.Web.MergedOptionsValidation.Validate(MergedOptions options)
presencelight    |    at Microsoft.Identity.Web.MicrosoftIdentityWebAppAuthenticationBuilderExtensions.<>c__DisplayClass5_0.<AddMicrosoftIdentityWebAppInternal>b__3(OpenIdConnectOptions options, IServiceProvider serviceProvider, IOptionsMonitor`1 mergedOptionsMonitor, IOptionsMonitor`1 msIdOptionsMonitor, IOptions`1 msIdOptions)
presencelight    |    at Microsoft.Extensions.Options.ConfigureNamedOptions`5.Configure(String name, TOptions options)
presencelight    |    at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
presencelight    |    at Microsoft.Extensions.Options.OptionsMonitor`1.<>c__DisplayClass10_0.<Get>b__0()
presencelight    |    at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
presencelight    | --- End of stack trace from previous location ---
presencelight    |    at System.Lazy`1.CreateValue()
presencelight    |    at System.Lazy`1.get_Value()
presencelight    |    at Microsoft.Extensions.Options.OptionsCache`1.GetOrAdd(String name, Func`1 createOptions)
presencelight    |    at Microsoft.Extensions.Options.OptionsMonitor`1.Get(String name)
presencelight    |    at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.InitializeAsync(AuthenticationScheme scheme, HttpContext context)
presencelight    |    at Microsoft.AspNetCore.Authentication.AuthenticationHandlerProvider.GetHandlerAsync(HttpContext context, String authenticationScheme)
presencelight    |    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
presencelight    |    at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.HandleException(HttpContext context, ExceptionDispatchInfo edi)
presencelight    | [19:35:16 ERR] Connection id "0HMG17B1M5ITI", Request id "0HMG17B1M5ITI:00000001": An unhandled exception was thrown by the application.
presencelight    | System.ArgumentNullException: IDW10106: The 'ClientId' option must be provided. 
presencelight    |    at Microsoft.Identity.Web.MergedOptionsValidation.Validate(MergedOptions options)
presencelight    |    at Microsoft.Identity.Web.MicrosoftIdentityWebAppAuthenticationBuilderExtensions.<>c__DisplayClass5_0.<AddMicrosoftIdentityWebAppInternal>b__3(OpenIdConnectOptions options, IServiceProvider serviceProvider, IOptionsMonitor`1 mergedOptionsMonitor, IOptionsMonitor`1 msIdOptionsMonitor, IOptions`1 msIdOptions)
presencelight    |    at Microsoft.Extensions.Options.ConfigureNamedOptions`5.Configure(String name, TOptions options)
presencelight    |    at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
presencelight    |    at Microsoft.Extensions.Options.OptionsMonitor`1.<>c__DisplayClass10_0.<Get>b__0()
presencelight    |    at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
presencelight    |    at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
presencelight    |    at System.Lazy`1.CreateValue()
presencelight    |    at System.Lazy`1.get_Value()
presencelight    |    at Microsoft.Extensions.Options.OptionsCache`1.GetOrAdd(String name, Func`1 createOptions)
presencelight    |    at Microsoft.Extensions.Options.OptionsMonitor`1.Get(String name)
presencelight    |    at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.InitializeAsync(AuthenticationScheme scheme, HttpContext context)
presencelight    |    at Microsoft.AspNetCore.Authentication.AuthenticationHandlerProvider.GetHandlerAsync(HttpContext context, String authenticationScheme)
presencelight    |    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
presencelight    |    at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
presencelight    |    at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.HandleException(HttpContext context, ExceptionDispatchInfo edi)
presencelight    |    at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
presencelight    |    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

**Comment by isaacrlevin** [comment]
Ugh, that is my bad. You need the config settings. Put this in appsettings.json

```
{
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft": "Information"
    }
  },
  "SendDiagnosticData": false,
  "AzureAd": {
    "Instance": "https://login.microsoftonline.com/",
    "TenantId": "common",
    "ClientId": "f8119f58-4523-44c1-ab72-b2e0c815bd6a",
    "CallbackPath": "/signin-oidc",
    "RedirectHost": "https://localhost:5001",
    "SignedOutCallbackPath ": "/signout-callback-oidc",
    "ClientSecret": "io2~p.3-2~x646_TMC-uo4tL9610mA2RxO"
  },
  "DownstreamApi": {
    "BaseUrl": "https://graph.microsoft.com/beta",
    "Scopes": "user.read presence.read offline_access"
  },
  "ApplicationInsights": {
    "InstrumentationKey": "63a1f0f1-4e30-4dd2-86dc-9acc718e675b"
  },
  "SnapshotCollectorConfiguration": {
    "IsEnabledInDeveloperMode": true,
    "ThresholdForSnapshotting": 1,
    "MaximumSnapshotsRequired": 3,
    "MaximumCollectionPlanSize": 50,
    "ReconnectInterval": "00:15:00",
    "ProblemCounterResetInterval": "1.00:00:00",
    "SnapshotsPerTenMinutesLimit": 1,
    "SnapshotsPerDayLimit": 30,
    "SnapshotInLowPriorityThread": true,
    "ProvideAnonymousTelemetry": true,
    "FailedRequestLimit": 3
  },
  "AppType": "Web",
  "AppVersion": "Local"
}
```

**Comment by CamSoper** [comment]
Well we're a lot closer.

Got it all built and working. Started with `docker-compose up -d`, connected, authed, and verified it was picking up statuses and sending them to my custom API.

Then I did a `docker-compose restart` and it restarted. I test-changed my Teams status, but it wasn't picked up.

So I went back to the browser tab with the web app and hit F5 and observed the network traffic. It never redirected to AAD, it just lit up and started working again. The downside is that I had to hit F5 in the browser before it'd work. 

(I also tested again to make sure.)

**Comment by isaacrlevin** [comment]
When you run it the 2nd time, can you do a screengrab of the console logs BEFORE you refresh the page, and than when you do? I have an idea what the issue is but want to confirm

**Comment by isaacrlevin** [comment]
@CamSoper 
This may be a challenge with how Microsoft Identity works. When you have a token cache, there is a requirement that you can access it with the account that the token represents. In the case when the app restarts, at start time it does not know the user account (as you "could" have multiple accounts). The reason why the browser refresh makes it all work is because of cookies.

So the flow is

- Token cache file is persisted, representing some user
- When app starts, it has no users, so it does not load the cache
- Popping the browser triggers a population of the user account
- Next Graph poll the cache is loaded and we are on our merry way

I am looking at my options of serializing the user account and persisting that is well, but I can assume that is a terrible practice. At lease if I have a serialized file with the account I can load that and maybe the cache gets read

**Comment by isaacrlevin** [comment]
@cmatskas can you help me hunt down what I might need to do here? Long story short I want to persist a user account in cache through a docker restart WITHOUT having to trigger the repopulation of that UserAccount? Here are the bits in code where I am messing interacting with Identity

https://github.com/isaacrlevin/presencelight/blob/main/src/PresenceLight.Razor/Services/UserAuthService.cs

Is what I am doing possible?

**Comment by cmatskas** [comment]
Hmm, probably not possible. Can you hit up our dev support team for this? HTTPS://Aka.ms/425Show/help. Ping me when you get your issue raised so I can chase up. Thx

**Comment by isaacrlevin** [comment]
Not possible after research :(
