### ISSUE TITLE
Error when attempting to run Blazor version on a Mac

### ISSUE THREAD

**Issue by gordonkennedy** [isaacrlevin/PresenceLight#91]
When I attempt to run the Blazor version 2.0.82 on Mac OS 10.14.6, I'm encountering the following error:
`A fatal error was encountered. The library 'libhostpolicy.dylib' required to execute the application was not found in '/Users/xxx/2.0.82_macOS/'.
Failed to run as a self-contained app.`

To launch it, I'm running `dotnet PresenceLight.exe` - I added the .exe extension to the executable since running 'dotnet PresenceLight' returned the following error:

```
Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET program, but dotnet-PresenceLight does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
```

In case it's helpful, here's the output from `dotnet --info`
```
.NET SDK (reflecting any global.json):
 Version:   5.0.100-preview.6.20318.15
 Commit:    4356580024

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.14
 OS Platform: Darwin
 RID:         osx.10.14-x64
 Base Path:   /usr/local/share/dotnet/sdk/5.0.100-preview.6.20318.15/

Host (useful for support):
  Version: 5.0.0-preview.6.20305.6
  Commit:  4ba9ecaabd

.NET SDKs installed:
  3.1.301 [/usr/local/share/dotnet/sdk]
  5.0.100-preview.6.20318.15 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-preview.6.20312.15 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.9 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-preview.6.20305.6 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

```
Any pointers on what I might be doing wrong?

**Comment by isaacrlevin** [comment]
I think there is an issue running PresenceLight starting in version 2.0.78. Can you try this version?

https://presencelight.blob.core.windows.net/worker-archive/macOS_Signed/2.0.75_macOS.zip

**Comment by gordonkennedy** [comment]
I just tested 2.0.75 and I'm encountering the same issue.

Full output (in case there's anything else helpful in there):
```
$ dotnet PresenceLight.exe 
Cannot use stream for resource [/Users/xxx/2.0.75_macOS/PresenceLight.deps.json]: No such file or directory
A fatal error was encountered. The library 'libhostpolicy.dylib' required to execute the application was not found in '/Users/g0k00l9/Repos/Reimagine/2.0.75_macOS/'.
Failed to run as a self-contained app.
  - The application was run as a self-contained app because '/Users/xxx/2.0.75_macOS/PresenceLight.runtimeconfig.json' was not found.
  - If this should be a framework-dependent app, add the '/Users/xxx/2.0.75_macOS/PresenceLight.runtimeconfig.json' file and specify the appropriate framework.
```

**Comment by gordonkennedy** [comment]
I just tested 2.0.75 and I'm encountering the same issue.

Full output (in case there's anything else helpful in there):
```
$ dotnet PresenceLight.exe 
Cannot use stream for resource [/Users/xxx/2.0.75_macOS/PresenceLight.deps.json]: No such file or directory
A fatal error was encountered. The library 'libhostpolicy.dylib' required to execute the application was not found in '/Users/xxx/2.0.75_macOS/'.
Failed to run as a self-contained app.
  - The application was run as a self-contained app because '/Users/xxx/2.0.75_macOS/PresenceLight.runtimeconfig.json' was not found.
  - If this should be a framework-dependent app, add the '/Users/xxx/2.0.75_macOS/PresenceLight.runtimeconfig.json' file and specify the appropriate framework.
```

**Comment by isaacrlevin** [comment]
Hmmm. Can you try one more thing? Can you uninstall .NET 5 Preview 6 and install Preview 4? I am aware of a bug that affects PresenceLight in P6 but haven't seen this one

**Comment by gordonkennedy** [comment]
Tested now with Preview 4, unfortunately with same result:

```
$ dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.100-preview.4.20258.7
 Commit:    65f0fc2cad

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.14
 OS Platform: Darwin
 RID:         osx.10.14-x64
 Base Path:   /usr/local/share/dotnet/sdk/5.0.100-preview.4.20258.7/

Host (useful for support):
  Version: 5.0.0-preview.4.20251.6
  Commit:  47ec733ba7

.NET SDKs installed:
  5.0.100-preview.4.20258.7 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.0-preview.4.20257.10 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.0-preview.4.20251.6 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

```
$ cd ~/xxx/2.0.75_macOS/
$ dotnet PresenceLight.exe 
Cannot use stream for resource [/xxx/2.0.75_macOS/PresenceLight.deps.json]: No such file or directory
A fatal error was encountered. The library 'libhostpolicy.dylib' required to execute the application was not found in '/xxx/2.0.75_macOS/'.
Failed to run as a self-contained app.
  - The application was run as a self-contained app because '/xxx/2.0.75_macOS/PresenceLight.runtimeconfig.json' was not found.
  - If this should be a framework-dependent app, add the '/xxx/2.0.75_macOS/PresenceLight.runtimeconfig.json' file and specify the appropriate framework.
```

**Comment by isaacrlevin** [comment]
Hrmmm. When was the last time it worked? :)

**Comment by gordonkennedy** [comment]
Oh this is the first time I've tried it :)
I tried searching online to find reports from others running it on Mac, but no luck. Perhaps I'm a trailblazer.

**Comment by isaacrlevin** [comment]
It worked on a friends Mac, but that was months ago. Looks like I need to
test :)

**Comment by gordonkennedy** [comment]
I'm wondering if it could be an issue with the build pipeline for the Mac version. [One thread regarding this error](https://github.com/dotnet/core/issues/1038#issuecomment-338316310) suggests you may get this error if you're trying to run the contents of the 'build' directory rather than the 'publish' directory. I'm not sure if that's a possibility here.

I will also try running it on my personal Mac to validate that this issue isn't specific to my work Mac.

**Comment by isaacrlevin** [comment]
That isn't it, seems that the file it is looking for isn't in the folder 
![image](https://user-images.githubusercontent.com/8878502/86969559-daac5f80-c122-11ea-9af8-f081df511596.png)

maybe just try to run the exe instead of the dotnet in front?

**Comment by gordonkennedy** [comment]
Interesting... running the executable looked more promising, but ended in an error with both versions:

v2.0.82:
```
Unhandled exception. System.IO.FileNotFoundException: Related assembly 'Microsoft.AspNetCore.Authentication.AzureAD.UI.Views' specified by assembly 'Microsoft.AspNetCore.Authentication.AzureAD.UI' could not be found in the directory /Users/xxx/2.0.82_macOS. Related assemblies must be co-located with the specifying assemblies.
File name: '/Users/xxx/2.0.82_macOS/Microsoft.AspNetCore.Authentication.AzureAD.UI.Views.dll'
   at Microsoft.AspNetCore.Mvc.ApplicationParts.RelatedAssemblyAttribute.GetRelatedAssemblies(Assembly assembly, Boolean throwOnError, Func`2 fileExists, Func`2 loadFile)
   at Microsoft.AspNetCore.Mvc.ApplicationParts.RelatedAssemblyAttribute.GetRelatedAssemblies(Assembly assembly, Boolean throwOnError)
   at Microsoft.AspNetCore.Authentication.AzureADAuthenticationBuilderExtensions.GetAdditionalParts()+MoveNext()
   at Microsoft.AspNetCore.Authentication.AzureADAuthenticationBuilderExtensions.<>c__DisplayClass6_0.<AddAdditionalMvcApplicationParts>b__0(ApplicationPartManager apm)
   at Microsoft.Extensions.DependencyInjection.MvcCoreMvcBuilderExtensions.ConfigureApplicationPartManager(IMvcBuilder builder, Action`1 setupAction)
   at Microsoft.AspNetCore.Authentication.AzureADAuthenticationBuilderExtensions.AddAdditionalMvcApplicationParts(IServiceCollection services)
   at Microsoft.AspNetCore.Authentication.AzureADAuthenticationBuilderExtensions.AddAzureAD(AuthenticationBuilder builder, String scheme, String openIdConnectScheme, String cookieScheme, String displayName, Action`1 configureOptions)
   at Microsoft.AspNetCore.Authentication.AzureADAuthenticationBuilderExtensions.AddAzureAD(AuthenticationBuilder builder, Action`1 configureOptions)
   at PresenceLight.Worker.Startup.ConfigureServices(IServiceCollection services)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.MethodInfoExtensions.InvokeWithoutWrappingExceptions(MethodInfo methodInfo, Object obj, Object[] parameters)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.InvokeCore(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass9_0.<Invoke>g__Startup|0(IServiceCollection serviceCollection)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.Invoke(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass8_0.<Build>b__0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.UseStartup(Type startupType, HostBuilderContext context, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass12_0.<UseStartup>b__0(HostBuilderContext context, IServiceCollection services)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at PresenceLight.Worker.Program.Main(String[] args)
Abort trap: 6
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
```


v2.0.75:
```
Unhandled exception. System.IO.FileNotFoundException: The configuration file 'AADSettings.json' was not found and is not optional. The physical path is '/Users/xxx/AADSettings.json'.
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.HandleException(ExceptionDispatchInfo info)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean reload)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load()
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at PresenceLight.Worker.Program.CreateHostBuilder(String[] args)
   at PresenceLight.Worker.Program.Main(String[] args)
Abort trap: 6
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
```

**Comment by isaacrlevin** [comment]
Yep, this is one I am aware of, I opened an issue here
https://github.com/dotnet/aspnetcore/issues/23710

**Comment by isaacrlevin** [comment]
Give version 2.0.86 a try, I downgraded the app to 3.1 and validated it works on Windows

**Comment by gordonkennedy** [comment]
Thanks @isaacrlevin! I just downloaded 3.0.1 and I was able to launch it. I got the authentication dialog, but now I'm awaiting approval from my company's AD admin. It's looking promising, though!

**Comment by isaacrlevin** [comment]
You shouldn't need AAD consent. Mind showing me a screen shot?

**Comment by gordonkennedy** [comment]
@isaacrlevin 👍 I've just sent you a DM on Twitter

**Comment by isaacrlevin** [comment]
We chatted offline. @gordonkennedy feel free to reopen if you have issues after the consent

**Comment by thomclae33** [comment]
I get a similar error on Mac:
`Error:
  An assembly specified in the application dependencies manifest (PresenceLight.deps.json) was not found:
    package: 'runtimepack.Microsoft.NETCore.App.Runtime.osx-x64', version: '5.0.4'
    path: 'libSystem.IO.Compression.Native.dylib'`

Trying to install the package manually did not solve the issue. Any suggestions?
